### PR TITLE
Implement dot notation email validation for gmail

### PR DESCRIPTION
**Pull request by mfikria**

### CODE REVIEW

**Comment by mfikria** [comment]
@maxceem i've update the PR. Please review it again thanks!

**Comment by mfikria** [comment]
@maxceem updated with:
1. change regex validation
2. update config for `compareEmail` function

**Comment by maxceem** [comment]
Noticed one more thing:

- If we have an invitation with email `test@GMAIL.com` and try to invite email `test@gmail.com` - these emails would be treated differently.

The reason for this is that the method `compareEmail` is not symmetrical: 
- `compareEmail(email1, email2) !== compareEmail(email2, email1)` - sometimes

**Comment by mfikria** [comment]
@maxceem i've updated the function:
1. fix regex for additional dot with '\.?' instead of '.?'
2. only allow gmail.com and googlemail.com as email domains
3. make email domain case insensitive

**Pull request merged**
