### PR TITLE
Fix for issue #133

### PR DESCRIPTION
**Pull request by thiyagu06**
I found new issue when testing postman collection. 
1. Creating project with timeline id
2. Project Upgrade end point

Those two scenarios end points are tracked in different folder in the postman collection.

### CODE REVIEW

**Comment by thiyagu06** [comment]
#133

**Comment by vikasrohit** [comment]
>I found new issue when testing postman collection.

Creating project with timeline id
Project Upgrade end point
Those two scenarios end points are tracked in different folder in the postman collection.

Didn't get it @thiyagu06 what exactly is the problem there? Problem in postman docs or the actual endpoints?

**Comment by coderReview** [comment]
I've also tried myself and probably it was some issue in his database.

**Comment by vikasrohit** [comment]
Okay, Thanks for the update.

**Pull request merged**
