### PR TITLE
[HOTFIX] [PROD] Post Release 2.4.1 - Protect billing account

### PR DESCRIPTION
**Pull request by maxceem**
Implementation for https://github.com/topcoder-platform/tc-project-service/issues/529

Corresponding fix has been merged to DEV for testing https://github.com/topcoder-platform/tc-project-service/pull/564.

This PR could be merged if we want to apply it as a hotfix, or it might be closed if we decide to go with a regular release.

### CODE REVIEW

**Comment by vikasrohit** [comment]
@maxceem I would like to combine #560  #561 also in the same patch or full release. So, lets get them also in this branch for now and if we need to make a patch release, we can release them together.

**Comment by maxceem** [comment]
ok @vikasrohit. I'm closing this PR and would raise a new one with all these fixes included.

**Comment by maxceem** [comment]
I'm reopening this PR as we decided not to include more functionality to the hotfix.

**Comment by vikasrohit** [comment]
@maxceem we can live with releasing it as regular release now. So, I guess we can keep the PR closed until it becomes urgent.

**Comment by maxceem** [comment]
Ok, closing it.

**Pull request closed without merging**
