### PR TITLE
Feature/project search update

### PR DESCRIPTION
**Pull request by gondzo**
Fixes project search (searching with status, project type) and adds support for ref code search (ref:term) and literal search("exact match")

### CODE REVIEW

**Comment by vikasrohit** [comment]
@gondzo this PR does not have fix for https://github.com/appirio-tech/connect-app/issues/2062, right?

**Comment by gondzo** [comment]
yes, it does. are we ok to merge this to dev?
should we release to prod as well as a hotfix?

**Comment by vikasrohit** [comment]
Yes, we are good to get it merged to dev. Not needed as hotfix on production.

**Comment by vikasrohit** [comment]
@gondzo If this PR takes care of https://github.com/appirio-tech/connect-app/issues/1954, we should remove open for pickup tag from that issue.

**Pull request merged**
