### PR TITLE
Limit draft phase update events to topcoder project members

### PR DESCRIPTION
**Pull request by gondzo**
@vikasrohit this one fixes https://github.com/topcoder-platform/tc-notifications/issues/85
we'll limit the notifications only to topcoder team if phase is not visible to customer (draft)

### CODE REVIEW

**Comment by vikasrohit** [comment]
Thank @gondzo It seems like we are still generating the events but just trying to hide them on front end by looking at  `allowedUser` field.

**Comment by gondzo** [comment]
generating events - yes
generating notifications - only for users in allowedUsers list (no need to filter in connect-app or emails)

**Comment by vikasrohit** [comment]
> generating notifications - only for users in allowedUsers list

Did I miss the changes in `tc-notifications` then?

**Comment by gondzo** [comment]
ugh, yes, I pushed straight to dev

https://github.com/topcoder-platform/tc-notifications/commit/176400534b4350c2a92aaeda1fb2c45cdd00ba0f
https://github.com/topcoder-platform/tc-notifications/commit/1e800921ed5e138cf2e1eb8f5f62f0ab5f554bf9

**Comment by vikasrohit** [comment]
Ohk. Got it.

**Comment by vikasrohit** [comment]
@gondzo I think there is some potential issue here. https://github.com/topcoder-platform/tc-notifications/commit/1e800921ed5e138cf2e1eb8f5f62f0ab5f554bf9#diff-c70adcc7eeb9e6a77abb22af0d363d5cR163 specifies `allowedUser` as string while https://github.com/topcoder-platform/tc-notifications/commit/1e800921ed5e138cf2e1eb8f5f62f0ab5f554bf9#diff-c70adcc7eeb9e6a77abb22af0d363d5cR203 as variable

**Comment by vikasrohit** [comment]
@gondzo I have patched (https://github.com/topcoder-platform/tc-notifications/pull/88/commits/d1eefb9b868e4302fa4fd270e6ffb361803962fa) the `tc-notifications` to use string instead of variable name for the issue mentioned above, let me know if you think that is not a desired change.

**Pull request merged**
