### PR TITLE
Issue #128

### PR DESCRIPTION
**Pull request by morehappiness**
Fix Issue #128

### CODE REVIEW

**Comment by vikasrohit** [comment]
@morehappiness could you please squash the changes in single commit? These change are potentially breaking, so I would like to revert them with single commit.

**Comment by vikasrohit** [comment]
Apologies, @morehappiness I didn't saw that you already had the squashed commit. I just saw the 28 files changed.

**Comment by vikasrohit** [comment]
@morehappiness we would the sql script to migrate the schema to have `deletedBy` column in multiple tables. Would you be able to create a separate PR for that?

**Comment by morehappiness** [comment]
What do you mean by ' squashed commit'? Yes, I will add deletedBy column in  sql script

**Comment by morehappiness** [comment]
@vikasrohit , do you mean to commit to branch 'feature/timeline-milestone-issue#128-soft-delete'

**Comment by morehappiness** [comment]
It seems that the new tables in 20180608_project_add_templateId_and_new_tables.sql already have the deletedBy column. But i do not see the table definition for projects, project_attachments, project_members

**Comment by vikasrohit** [comment]
> What do you mean by ' squashed commit'? Yes, I will add deletedBy column in sql script

Squashed means, single commit for the change which you have already done. Thank you.

> @vikasrohit , do you mean to commit to branch 'feature/timeline-milestone-issue#128-soft-delete'

No, that I created in assumption that you have committed more than 1 commit for the change. But it is not needed now as you have already committed only single commit.

>It seems that the new tables in 20180608_project_add_templateId_and_new_tables.sql already have the deletedBy column. But i do not see the table definition for projects, project_attachments, project_members

Yes, those are missing as initially the project used sequelize sync method to create the tables in database even on production which have stopped using later to avoid unwanted db migrations automatically. You can add a new migration SQL with today's date and just add the alter commands needed to add the new columns to the tables.

**Comment by morehappiness** [comment]
> Yes, those are missing as initially the project used sequelize sync method to create the tables in database even on production which have stopped using later to avoid unwanted db migrations automatically. You can add a new migration SQL with today's date and just add the alter commands needed to add the new columns to the tables.

i see the pull request has been accepted. Do you still need the  projects, project_attachments, project_members to add deletedBy column for migration?

**Comment by vikasrohit** [comment]
I created it. I think we are good now.

**Pull request merged**
