### PR TITLE
Feature/file transfer s3 improvements

### PR DESCRIPTION
**Pull request by maxceem**
2 improvements have been done to file transfer:
- use AWS SDK instead of AWS CLI vi exec for transferring files between buckets
- remove a redundant call for `${fileServiceUrl}uploadurl` which we don't need anymore in Project Service

### CODE REVIEW

**Comment by maxceem** [comment]
@vikasrohit it has been tested on DEV and works good for me. So I propose to merge it to DEV for the release.

If we don't release, we can create a hotfix out of the `feature/file-transfer-s3-improvements` branch.

**Comment by vikasrohit** [comment]
Just to double sure, we now don't call file service at all from project service, right?

**Comment by maxceem** [comment]
We still call it to get a `downloadUrl` https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/attachments/create.js#L100. We cannot avoid it.

Though now we don't have to call endpoint for getting `uploadUrl` anymore it left from the previous implementation.

**Comment by vikasrohit** [comment]
Okay. I think we can avoid call for `downloadUrl` as well in near future, may be by having this as utility method in tc-core-lib-js.

**Pull request merged**
